# Limit on the number of recent articles
recent_posts_limits: 4

# The categories and order displayed on the home page
index_categories:
  - 常规检测

# Home recommended posts
index_recommends:
  - 钢筋扫描


# Related popular posts
# Dependencies: https://github.com/tea3/hexo-related-popular-posts
related_posts:
  enable: true
  title: Related
  params:
    maxCount: 4
    #PPMixingRate: 0.0
    #isDate: false
    #isImage: false
    #isExcerpt: false

top_posts:
  enable: true
  title: Top
  params:
    maxCount: 4
    PPMixingRate: 1.0
